// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RentACar.Infrastructure.Data;

#nullable disable

namespace RentACar.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260405123148_SeedCars")]
    partial class SeedCars
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("RentACar.Domain.Entities.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CarId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("RentACar.Domain.Entities.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<string>("FuelType")
                        .HasColumnType("longtext");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("PricePerDay")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Seats")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Transmission")
                        .HasColumnType("longtext");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "BMW",
                            Category = 3,
                            FuelType = "Benzin",
                            ImageUrl = "https://images.unsplash.com/photo-1555215695-3004980ad54e?w=600&q=80",
                            Model = "7 Series",
                            PricePerDay = 4500m,
                            Seats = 5,
                            Status = 0,
                            Transmission = "Otomatik",
                            Year = 2024
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Mercedes",
                            Category = 3,
                            FuelType = "Hibrit",
                            ImageUrl = "https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?w=600&q=80",
                            Model = "S-Class",
                            PricePerDay = 5200m,
                            Seats = 5,
                            Status = 0,
                            Transmission = "Otomatik",
                            Year = 2024
                        },
                        new
                        {
                            Id = 3,
                            Brand = "Audi",
                            Category = 3,
                            FuelType = "Dizel",
                            ImageUrl = "https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=600&q=80",
                            Model = "A8",
                            PricePerDay = 4200m,
                            Seats = 5,
                            Status = 0,
                            Transmission = "Otomatik",
                            Year = 2023
                        },
                        new
                        {
                            Id = 4,
                            Brand = "Porsche",
                            Category = 3,
                            FuelType = "Hibrit",
                            ImageUrl = "https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=600&q=80",
                            Model = "Cayenne",
                            PricePerDay = 6000m,
                            Seats = 5,
                            Status = 0,
                            Transmission = "Otomatik",
                            Year = 2024
                        },
                        new
                        {
                            Id = 5,
                            Brand = "Toyota",
                            Category = 2,
                            FuelType = "Dizel",
                            ImageUrl = "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=600&q=80",
                            Model = "Land Cruiser",
                            PricePerDay = 2800m,
                            Seats = 7,
                            Status = 0,
                            Transmission = "Otomatik",
                            Year = 2023
                        },
                        new
                        {
                            Id = 6,
                            Brand = "Nissan",
                            Category = 2,
                            FuelType = "Benzin",
                            ImageUrl = "https://images.unsplash.com/photo-1609521263047-f8f205293f24?w=600&q=80",
                            Model = "Qashqai",
                            PricePerDay = 1600m,
                            Seats = 5,
                            Status = 0,
                            Transmission = "Otomatik",
                            Year = 2023
                        },
                        new
                        {
                            Id = 7,
                            Brand = "Hyundai",
                            Category = 2,
                            FuelType = "Hibrit",
                            ImageUrl = "https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=600&q=80",
                            Model = "Tucson",
                            PricePerDay = 1750m,
                            Seats = 5,
                            Status = 0,
                            Transmission = "Otomatik",
                            Year = 2024
                        },
                        new
                        {
                            Id = 8,
                            Brand = "Peugeot",
                            Category = 2,
                            FuelType = "Dizel",
                            ImageUrl = "https://images.unsplash.com/photo-1541899481282-d53bffe3c35d?w=600&q=80",
                            Model = "3008",
                            PricePerDay = 1500m,
                            Seats = 5,
                            Status = 0,
                            Transmission = "Otomatik",
                            Year = 2023
                        },
                        new
                        {
                            Id = 9,
                            Brand = "Ford",
                            Category = 4,
                            FuelType = "Dizel",
                            ImageUrl = "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80",
                            Model = "Tourneo",
                            PricePerDay = 2200m,
                            Seats = 9,
                            Status = 0,
                            Transmission = "Manuel",
                            Year = 2023
                        },
                        new
                        {
                            Id = 10,
                            Brand = "Volkswagen",
                            Category = 4,
                            FuelType = "Dizel",
                            ImageUrl = "https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?w=600&q=80",
                            Model = "Caravelle",
                            PricePerDay = 2400m,
                            Seats = 9,
                            Status = 0,
                            Transmission = "Otomatik",
                            Year = 2022
                        },
                        new
                        {
                            Id = 11,
                            Brand = "Volkswagen",
                            Category = 1,
                            FuelType = "Benzin",
                            ImageUrl = "https://images.unsplash.com/photo-1471444928139-48c5bf5173f8?w=600&q=80",
                            Model = "Golf",
                            PricePerDay = 1100m,
                            Seats = 5,
                            Status = 0,
                            Transmission = "Manuel",
                            Year = 2023
                        },
                        new
                        {
                            Id = 12,
                            Brand = "Toyota",
                            Category = 1,
                            FuelType = "Hibrit",
                            ImageUrl = "https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?w=600&q=80",
                            Model = "Corolla",
                            PricePerDay = 1050m,
                            Seats = 5,
                            Status = 0,
                            Transmission = "Otomatik",
                            Year = 2024
                        },
                        new
                        {
                            Id = 13,
                            Brand = "Renault",
                            Category = 1,
                            FuelType = "Dizel",
                            ImageUrl = "https://images.unsplash.com/photo-1580273916550-e323be2ae537?w=600&q=80",
                            Model = "Megane",
                            PricePerDay = 950m,
                            Seats = 5,
                            Status = 0,
                            Transmission = "Manuel",
                            Year = 2023
                        },
                        new
                        {
                            Id = 14,
                            Brand = "Renault",
                            Category = 0,
                            FuelType = "Benzin",
                            ImageUrl = "https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?w=600&q=80",
                            Model = "Clio",
                            PricePerDay = 750m,
                            Seats = 5,
                            Status = 0,
                            Transmission = "Manuel",
                            Year = 2023
                        },
                        new
                        {
                            Id = 15,
                            Brand = "Fiat",
                            Category = 0,
                            FuelType = "Benzin",
                            ImageUrl = "https://images.unsplash.com/photo-1590362891991-f776e747a588?w=600&q=80",
                            Model = "Egea",
                            PricePerDay = 700m,
                            Seats = 5,
                            Status = 0,
                            Transmission = "Manuel",
                            Year = 2024
                        },
                        new
                        {
                            Id = 16,
                            Brand = "Hyundai",
                            Category = 0,
                            FuelType = "Benzin",
                            ImageUrl = "https://images.unsplash.com/photo-1494976388531-d1058494cdd8?w=600&q=80",
                            Model = "i20",
                            PricePerDay = 720m,
                            Seats = 5,
                            Status = 0,
                            Transmission = "Manuel",
                            Year = 2023
                        },
                        new
                        {
                            Id = 17,
                            Brand = "Opel",
                            Category = 0,
                            FuelType = "Benzin",
                            ImageUrl = "https://images.unsplash.com/photo-1502877338535-766e1452684a?w=600&q=80",
                            Model = "Corsa",
                            PricePerDay = 680m,
                            Seats = 5,
                            Status = 0,
                            Transmission = "Manuel",
                            Year = 2023
                        },
                        new
                        {
                            Id = 18,
                            Brand = "Peugeot",
                            Category = 0,
                            FuelType = "Elektrik",
                            ImageUrl = "https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?w=600&q=80",
                            Model = "208",
                            PricePerDay = 710m,
                            Seats = 5,
                            Status = 0,
                            Transmission = "Otomatik",
                            Year = 2024
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RentACar.Domain.Entities.Booking", b =>
                {
                    b.HasOne("RentACar.Domain.Entities.Car", "Car")
                        .WithMany("Bookings")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Car");
                });

            modelBuilder.Entity("RentACar.Domain.Entities.Car", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
